version: '3.8'

services:
  auth-service:
    image: camilobr89/auth-service:${TAG} # Utiliza la imagen desde un registro, asegúrate de construirla y etiquetarla en tus pipelines.
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE} # Ajusta el perfil de Spring basado en la variable de entorno.
      DB_NAME: ${DB_NAME}               # Nombre de la base de datos.
      DB_USER: ${DB_USER}               # Usuario de la base de datos.
      DB_PASSWORD: ${DB_PASSWORD}       # Contraseña de la base de datos.
    ports:
      - "${PORT}:8081"                  # Puerto para el servicio de Spring Boot.
      - "${DB_PORT}:5432"               # Puerto para PostgreSQL si es necesario.

