version: '3.8'

services:
  auth-service:
    build: .
    image: auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_NAME=prod_db
      - DB_USER=prod_user
      - DB_PASSWORD=prod_password
      - API_KEY=${API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: auth-db
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
