spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/prod_db
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password


jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

api:
  api.key: ${API_KEY}


logging:
  level:
    org.springframework.web.filter.CorsFilter: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.security: DEBUG


server:
  port: 8082