spring.application.name=my-banking-app-authentication-service

server:
    port: 8081

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/authdb
        username: postgres
        password: 1234
jpa:
    hibernate:
        ddl-auto: update
security:
    user:
        name: admin
        password: admin
