spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/staging_db
    username: staging_user
    password: staging_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: user
      password: password

server:
  port: 8081
