name: CI/CD Pipeline - Staging

on:
  push:
    branches:
      - 'staging'
      - 'staging/**'
      - 'BANK_**'
      - 'BANK_*/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push staging image
        run: |
          docker buildx build --push --tag ${{ secrets.DOCKER_USERNAME }}/auth-service:staging .

      - name: Debug SSH Key
        run: |
          echo "${{ secrets.VPS_PRIVATE_KEY }}" | head -c 20

      - name: SSH to VPS and deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/auth-service:staging
            docker stop auth-service-staging || true
            docker rm auth-service-staging || true
            docker run -d --name auth-service-staging -p 8081:8081 -p 5432:5432 -e SPRING_PROFILE=staging ${{ secrets.DOCKER_USERNAME }}/auth-service:staging